<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

	<title>{{ subject }}</title>

</head>
 
<body bgcolor="#FFFFFF" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; -webkit-font-smoothing:antialiased; -webkit-text-size-adjust:none; width: 100%!important; height: 100%;">

	<!-- HEADER -->
	<table class="head-wrap" bgcolor="#e91e63" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%;">
		<tr style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
			<td style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;"></td>
			<td class="header container" style="padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; display:block!important; max-width:600px!important; margin:0 auto!important; clear:both!important;" >
				<div class="content" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; padding:15px; max-width:600px; margin:0 auto; display:block;">
					<table bgcolor="#e91e63" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%;">
						<tr style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
							<td style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; border-top: 1px solid rgb(215,215,215); padding-top:15px; font-size:10px; font-weight: bold;">
								<img src="http://{{host}}/common/assets/img/favicons/favicon-96x96.png" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; max-width: 80px; float: left;"/>
								<div style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; color: white; margin-left: 30px; float: left; font-weight: bold; line-height: 80px; font-size: 32px;">La MAM'Oz</div>
							</td>
						</tr>
					</table>
				</div>
			</td>
			<td style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">

			</td>
		</tr>
	</table><!-- /HEADER -->


	<!-- BODY -->
	<table class="body-wrap" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%;">
		<tr style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
			<td style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;"></td>
			<td class="container" bgcolor="#FFFFFF" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; display:block!important; max-width:600px!important; margin:0 auto!important; clear:both!important;">
				<div class="content" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
				<table style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; width: 100%;">
					<tr style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
						<td style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
							<h3 style="margin:0; padding:0; font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; line-height: 1.1; margin-bottom:15px; color:#000; font-weight:500; font-size: 27px;" >{{title}}</h3>
							<p class="lead" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size:17px;">{{message1}}</p>
							<p style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">{{message2}}</p>
							<!-- Callout Panel -->
							<p class="callout" style="margin:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; padding:15px; background-color:#f06292; margin-bottom: 15px; color: white;">
								{{message3}} <a href="{{link}}" style="margin:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-weight:bold; color: white;">Cliquer ici! &raquo;</a>
							</p><!-- /Callout Panel -->

							<!-- social & contact -->
							<table class="social" width="100%" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; background-color: #f06292; color: white;">
								<tr style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
									<td style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">
										<!-- column 2 -->
										<table align="left" class="column" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; float:left; width: 280px; min-width: 279px;">
											<tr style="margin:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; padding: 15px;">
												<td style="margin:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; padding: 15px;">
													<h5 style="margin:0; padding:0; font-family: 'HelveticaNeue-Light', 'Helvetica Neue Light', 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; line-height: 1.1; margin-bottom:15px; color: white; font-weight:900; font-size: 17px;">Contact Info:</h5>
													<p style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; color: white;">
														Tel:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
														<strong><a href="tel:0561461017" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;">05.61.46.10.17</a></strong>
														<br/>
														Email:&nbsp;
														<strong><a href="mailto:laadmin31@gmail.com" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; color: white;">laadmin31@gmail.com</a></strong></p>
												</td>
											</tr>
										</table><!-- /column 2 -->

										<span class="clear" style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;"></span>

									</td>
								</tr>
							</table><!-- /social & contact -->

						</td>
					</tr>
				</table>
				</div><!-- /content -->

			</td>
			<td style="margin:0; padding:0; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;"></td>
		</tr>
	</table><!-- /BODY -->

</body>
</html>